module.exports = [
	"red", "green", "blue", "orange", "purple", "gray", "cyan", 
	"black", "white", "golden", "pink", "yellow", "indigo", "plum",
	"lime", "teal", "tan", "ivory",
	
	"curved", "deep", "even", "flat", "hilly", "jagged", 
	"round", "square", "steep", "thick", "thin", 
	"uneven", "big", "fat", "huge", "large", 
	"little", "long", "medium", "narrow", "petite", 
	"short", "skinny", "small", "tall", "tiny", 
	"wide", "cooing", "faint", "harsh", "hushed", 
	"husky", "loud", "mute", "noisy", "quiet", 
	"raspy", "shrill", "silent", "soft", "afraid", 
	"angry", "awful", "bad", "bored", "creepy", 
	"cruel", "eerie", "evil", "fierce", "guilty", 
	"hungry", "hurt", "ill", "lonely", "mad", 
	"safe", "scared", "shy", "sleepy", "sore", 
	"tense", "tired", "upset", "weary", "wicked", 
	"calm", "fair", "fine", "OK", "alert", 
	"amused", "brave", "bright", "eager", "elated", 
	"funny", "gentle", "good", "happy", "jolly", 
	"kind", "lucky", "proud", 
	"silly", "well", "witty", "alert", "blonde", 
	"bloody", "bright", "clean", "clear", "cloudy", 
	"cute", "dark", "dirty", "drab", "dull", 
	"fancy", "filthy", "homely", "light", "misty", 
	"muddy", "plain", "poised", "quaint", "scary", 
	"shiny", "smoggy", "stormy", "ugly"
]