module.exports = [
	"birds",  "hen", "cat", "kitten", "chicken", 
	"rooster", "hen", "chick", "cow", 
	"cattle", "bull", "cow", "calf", "dog", 
	"puppy", "elephant", "fish", "fox",
	"horse", "stallion", "foal", "kangaroo", 
	"buck", "lion", "cub", "monkey", "penguin",
	"pig", "rabbit", "bunny", "rabbit", "sheep", 
	"ram", "lamb", "tiger", "whale", "wolf", "bird", 
	
	"kim", "kendall", "jenner", "nicky", "hilton", 
	"deeley", "adam", "levine", "johnny", "depp", 
	"chris", "martin", "khloe", "selena", "gomez", 
	"simon", "cowell", "louis", "will", "ferrell", 
	"kate", "upton", "gigi", "audrina", 
	"lamar", "odom", "behati", "cara", "adam", 
	"sandler", "bella", "hadid", "north", "west", 
	"gwen", "stefani", "zayn", "malik", "taylor", 
	"swift", "elton", "john", "joel", "madden", 
	"maria", "shriver", "mark", "patrick", "arnold", 
	"blake", "shelton", "amber", "rose", "kanye", 
	"west", "drake", "ryan", "sarah", "jessica", 
	"parker", "avril", "lavigne", "calvin", "harris", 
	"justin", "ed", "sheeran", "jenny", "miley", 
	"cyrus", "niall", "horan", "dave", "navarro", 
	"carly", "rae", "jepsen", "justin", "bieber", 
	"david", "beckham", "jaime", "king", "britney", 
	"spears", "liam", "bradley", "cooper", "gwyneth", 
	"paltrow", "joe", "jonas", "josh", "groban", 
	"miranda", "kerr", "karlie", "kloss", "tyra", 
	"banks", "heidi", "klum", "nicole", "chris", 
	"brown", "scott", "disick", "rita", "ora", 
	"kris", "jenner",  "cat",
]